### PR TITLE
Lucap1211

### PR DESCRIPTION
**Pull request by lucap1211**
Adding my analysis link about Anchorage. AK

### CODE REVIEW

**Comment by thku8507** [comment]
this looks great!

**Comment by thku8507** [comment]
didn't mean to close the pull request--adding my review now

**Review by thku8507 — APPROVED** [review]
this looks great!

**Comment by JulesMRuef** [comment]
Looks great! Nice work

**Review by eculler — COMMENTED** [review]
Really nice work, @lucap1211 ! This is a very strong trend - 5 degrees in 70 years - it really exemplifies the much more extreme warming closer to the poles.

**Pull request merged**
