### PR TITLE
Lamont README.md

### PR DESCRIPTION
**Pull request by ellenalamont17**
#98 Submitted yesterday for amendment to the README.md with portfolio address

### CODE REVIEW

**Comment by nbol48** [comment]
Looks good!

**Review by nbol48 — COMMENTED** [review]
Looks good!

**Review by megan8617 — APPROVED** [review]
Yup, I see Ellen Lamont's additions, looks good

**Review by peterkobylarz — APPROVED** [review]

**Comment by ellenalamont17** [comment]
This is saying that I have conflicts, but I am not sure how to resolve them. When I click the "Resolve Conflicts" button, I can see the Readme code, but it's not clear what the identified error is and how to change it so that the conflict can be resolved.

**Comment by peterkobylarz** [comment]
@ellenalamont17 You have to delete the conflict markers. Basically all of row 15, 17, and 24. Then the resolve conflict button will be clickable. See item 4 on this page for examples of the conflict markers:

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

**Comment by eculler** [comment]
@ellenalamont17 No worries - I will be resolving the merge conflicts in this repository when I merge! You won't be able to keep up with them anyway, because other peoples' changes are coming in simultaneously. In software world, this is one of the jobs of a project manager every few weeks - to make sure that everyone's changes can get merged.

Nice work!

**Pull request merged**
