### PR TITLE
pull request

### PR DESCRIPTION
**Pull request by millie-spencer**
Creating pull request - Scavenger Hunt

### CODE REVIEW

**Comment by eculler** [comment]
@millie-spencer Nice job making a pull request! It looks like you pulled in all the main branch changes here, but I don't actually see your change to the README. Can you go ahead and:

1. Switch to your branch
2. Add yourself to the README table, tagging me (@eculler)

This Pull Request should automatically update, and I'll merge it.

**Comment by millie-spencer** [comment]
Hi @eculler , thanks for commenting! I'm confused by what you're asking me to do - what do you mean by the README "table"? I thought I was just supposed to update the readme on my personal page but might not have done that right

**Comment by eculler** [comment]
Oh I see! If you change the README in your repository that you made, you can't include that in a pull request to this repository (Earth-Analytics-Intro-2023).  So, for the scavenger hunt, the idea is that you will change the Earth-Analytics-Intro-2023 repository README, and then make a pull request, again in the Earth-Analytics-Intro-2023 repository. Since you've already made the pull request it should update automatically when you make your change.

For the portfolio assignment, you will edit the repository you made, including the README if you like. But since it's your repository and you are not collaborating there's no need for a branch or a pull request. If that's not making sense yet, I should have a video for you about GitHub in a few days, or you can bring it up in section.

**Comment by eculler** [comment]
@millie-spencer Looks like I've got two Pull Requests (PRs) from you, so I'm guessing the other one is what I'm looking for. This one is merging the main branch into your branch, which you should be able to merge yourself, but doesn't change the home page. To make a change to the main branch, you can check out the [How To page in the Wiki](https://github.com/earthlab-education/Earth-Analytics-2023-01-Intro/wiki/How-to...), and/or the video I posted to Discussions (you should have an email about that one)

**Pull request merged**
