### PR TITLE
Add my info to main README.md

### PR DESCRIPTION
**Pull request by lucap1211**
I do not have a view pull request option as the tutorial video describes, but I can create a new pull request. I hope this is what I am supposed to do to add my changes to the main branch. Thanks for your review and help!

### CODE REVIEW

**Review by ellenalamont17 — APPROVED** [review]
Website looks nice and the readme submission looks good. Only comment is that you misspelled geography on your website. Nice work.

**Comment by lucap1211** [comment]
Thanks for your time checking it! I corrected my mistake.

**Comment by eculler** [comment]
> I do not have a view pull request option as the tutorial video describes, but I can create a new pull request. I hope this is what I am supposed to do to add my changes to the main branch. Thanks for your review and help!

Looks good to me @lucap1211 !

**Comment by aholcomb23** [comment]
### Website and readme.md ### 
The readme.md looks **good**

**Pull request merged**
