### PR TITLE
Add links including final project #626

### PR DESCRIPTION
**Pull request by eggvoice**

### CODE REVIEW

**Comment by eggvoice** [comment]
See issue #335 and #339

**Comment by millie-spencer** [comment]
looks good to me!

**Review by ellenalamont17 — APPROVED** [review]
Nice analysis. I might recommend adding a location in your header. It says the Caldor Fire but does not indicate where that is located. Only after I scroll down further do I see an indication that it is near Lake Tahoe. With earth data, everything is tied to location, Stating that location makes it easier for the reader to gain some context. Also, your plots have titles but no real interpretative descriptions. Maybe consider adding after each graph/immage.

**Review by taylor-obrien — APPROVED** [review]
Looks great, Ed!

**Comment by eggvoice** [comment]
#444

**Comment by eggvoice** [comment]
#568

**Comment by eggvoice** [comment]
@eculler can you merge this one too?? Thank you!!

**Pull request merged**
