### PR TITLE
Jsmi374

### PR DESCRIPTION
**Pull request by jsmi374**
@nquarder  merge analysis to main #157

### CODE REVIEW

**Review by eggvoice — APPROVED** [review]
lgtm!

**Review by nquarder — APPROVED** [review]
@jsmi374 nice work with this code!

**Review by peterkobylarz — APPROVED** [review]
looks good James

**Review by eculler — COMMENTED** [review]
@jsmi374 excellent work! I love your style of science writing - it's really clear why this analysis is important in New Orleans all the way through.

I just have a couple of formatting notes:
- It looks like you had some trouble getting your link to work in the text. Using Markdown if would look like `The People of the Isle de Jean Charles, Became America's First Climate Refugees`
- I don't think that you need to set the hvplot extension to bokeh at all, but if you do you could consider doing so in your plotting cell so that the logo shows up near the plot or not at all.

**Pull request merged**
