### PR TITLE
Adriannaluger NCEI submission

### PR DESCRIPTION
**Pull request by Adriannaluger**

### CODE REVIEW

**Review by misterskye — CHANGES_REQUESTED** [review]
Good morning Adrianna,
Everything looks good...The site loads up and the plot is there.  The only thing you forgot was to update your 'Site Info' to NY.   Other than that it looks great

**Review by nbol48 — APPROVED** [review]
Looks great Adri! Agreed on a quick update of the Site Info, and it will be good to go.

**Review by Adriannaluger — COMMENTED** [review]
I updates my site info (hopefully successfully).

**Comment by Adriannaluger** [comment]
Sorry, I am having troubles updating it. Ill let you know when I have it figured out.

**Comment by Adriannaluger** [comment]
Alright, everything should be good now! Let me know if it shows the updates on your end as well.

**Review by misterskye — APPROVED** [review]

**Comment by misterskye** [comment]
Beautiful!!!!

**Comment by Adriannaluger** [comment]
@eculler complete :)

**Review by eculler — COMMENTED** [review]
Great work @Adriannaluger , this looks fantastic! And I like your headline.

The next step to improving this as a portfolio page or blog post in my opinion would be to take a look at your Site Information. You mention inequality here, which I think could be very relevant to temperature rise, but you don't make that connection for the reader.

You could also consider using headline-style headers for your text as well as your plot, rather than a description of what is in the section (e.g. "A century of temperature data in New York highlights long-term changes" instead of "Data Source")

**Pull request merged**
