### PR TITLE
Thku8507 NCEI submission

### PR DESCRIPTION
**Pull request by thku8507**

### CODE REVIEW

**Review by annieM459 — COMMENTED** [review]
Hi! This looks great. I would recommend adding a data citation as well as some sort of headline.

**Comment by JulesMRuef** [comment]
Looks good!

**Review by annieM459 — COMMENTED** [review]
Looks so great! Nice work

**Comment by cmq879** [comment]
Hello. Your page looks good. The Silverthorne photo isn't displaying on the page. One other tiny suggestion for future plots is to rename the series in the legend (instead of "temperature_f").  We are supposed to be reviewing the page, correct? Or should I look at the code in your repo?

**Comment by eculler** [comment]
@cmq879 - when doing these reviews, please go to Files Changed and add an Approve review with your comment. Makes it easier for me to see that you have completed your review!

**Review by eculler — COMMENTED** [review]
@thku8507 great work! I like that you look at the summer maximum temperatures - it makes sense to focus on one part of the year when looking at extremes, since the implications can be very different.

I'd recommend a headline rather than a description for your portfolio page - you could use it as the header instead of 'Summit County Summer Temperature Trends', or include an additional header for the plot.

For some reason your image isn't rendering - looks like perhaps you copied and pasted the image in? You can feel free to set the link directly to the wikimedia commons link.

If you would like to remove the legend for a single series plot using `pandas`, you can set `legend=False`

**Pull request merged**
