### PR TITLE
Jules m ruef NCEI submission

### PR DESCRIPTION
**Pull request by JulesMRuef**

### CODE REVIEW

**Comment by alexiemillikin** [comment]
Looks great to me--nice work!

**Review by alexiemillikin — APPROVED** [review]
Looks great to me--nice work!

**Review by eggvoice — APPROVED** [review]
lgtm!

**Review by aholcomb23 — COMMENTED** [review]
Nice work!

**Review by eculler — COMMENTED** [review]
@JulesMRuef this is really fantastic! Your site description is very grounded in the analysis - it's clear why I'm reading the analysis all the way through (we'll be referring to this technique as messaging this year if you don't already use that term). It's already very good, but I think you could improve your messaging by linking back to the analysis you're doing more frequently in the text. You could also include some information about the impacts of sea ice on local communities and wildlife.

**Pull request merged**
