### PR TITLE
Update ncei_temperatures.md with Ed's analysis link #155

### PR DESCRIPTION
**Pull request by eggvoice**

### CODE REVIEW

**Review by peterkobylarz — APPROVED** [review]
nice work, Ed! It looks good

**Comment by JulesMRuef** [comment]
Great job!

**Comment by eggvoice** [comment]
@JulesMRuef I think you accidentally closed my pull request. If you can, I still need another approval before I can merge this into the main branch. Thanks for reviewing earlier!

**Review by advythr — APPROVED** [review]
Looks great!

**Review by eculler — COMMENTED** [review]
Looks great, @eggvoice - nice work on the link, it takes me right to the analysis.

I like your data description in the Fun Fact section, especially the interactive prompt with Google Maps! I think that your headline could emphasize your observations more, by skipping the indirect language 'the observed years'

**Pull request merged**
